apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.project_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang
        image: {{cookiecutter.project_name}}-k8s
